services:
  hoit-app:
    image: hoit-app:latest
    container_name: hoit-app
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
      - rabbit-mq
    restart: unless-stopped
    networks:
      - hoit-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass han2024llm
    restart: unless-stopped
    networks:
      - hoit-network

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=han2024llm
    restart: unless-stopped
    networks:
      - hoit-network
    # 볼륨 권한 문제로 임시 제거
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP
      - '443:443'    # HTTPS
      - '81:81'      # 관리 웹 인터페이스
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - hoit-network   # 🔧 이 줄 추가!

networks:
  hoit-network:
    driver: bridge